---
- name: Fixed MySQL Setup
  hosts: db
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL Server with longer timeout
      apt:
        name: mysql-server
        state: present
      async: 300  # 5 minutes max
      poll: 30    # check every 30 seconds

    - name: Wait for MySQL installation to complete
      async_status:
        jid: "{{ ansible_job_id }}"
      register: mysql_job
      until: mysql_job.finished
      retries: 10
      delay: 10

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Create test database
      mysql_db:
        name: devops_app
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Show success message
      debug:
        msg: "✅ MySQL installed and database 'devops_app' created!"