---
- name: Setup HAProxy on Port 8080
  hosts: lb
  become: yes

  tasks:
    - name: Stop HAProxy
      systemd:
        name: haproxy
        state: stopped

    - name: Configure HAProxy on port 8080
      copy:
        content: |
          global
              daemon
              maxconn 256

          defaults
              mode http
              timeout connect 5000ms
              timeout client 50000ms
              timeout server 50000ms

          frontend http_front
              bind *:8080
              stats uri /haproxy?stats
              default_backend http_back

          backend http_back
              balance roundrobin
              server web1 192.168.56.10:8080 check
        dest: /etc/haproxy/haproxy.cfg

    - name: Start HAProxy
      systemd:
        name: haproxy
        state: started
        enabled: yes

    - name: Wait for port 8080
      wait_for:
        port: 8080
        delay: 5
        timeout: 30

    - name: Test locally
      shell: curl -s http://localhost:8080 | head -n 5
      register: test

    - name: Show success
      debug:
        msg:
          - "✅ HAProxy running on port 8080!"
          - "🌐 Access via: http://192.168.56.12:8080"
          - "📊 Stats: http://192.168.56.12:8080/haproxy?stats"
          - "Test output: {{ test.stdout }}"